# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\UI\adb.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 593)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.get_Activity_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.get_Activity_Butt.setGeometry(QtCore.QRect(430, 90, 151, 28))
        self.get_Activity_Butt.setObjectName("get_Activity_Butt")
        self.packName_text = QtWidgets.QTextEdit(self.centralWidget)
        self.packName_text.setGeometry(QtCore.QRect(10, 90, 401, 31))
        self.packName_text.setObjectName("packName_text")
        self.install_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.install_Butt.setGeometry(QtCore.QRect(470, 140, 151, 28))
        self.install_Butt.setObjectName("install_Butt")
        self.packPath_text = QtWidgets.QTextEdit(self.centralWidget)
        self.packPath_text.setGeometry(QtCore.QRect(10, 130, 401, 51))
        self.packPath_text.setObjectName("packPath_text")
        self.uninstall_packName_text = QtWidgets.QTextEdit(self.centralWidget)
        self.uninstall_packName_text.setGeometry(QtCore.QRect(10, 190, 401, 31))
        self.uninstall_packName_text.setObjectName("uninstall_packName_text")
        self.uninstall_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.uninstall_Butt.setGeometry(QtCore.QRect(420, 190, 191, 28))
        self.uninstall_Butt.setObjectName("uninstall_Butt")
        self.get_RAM_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.get_RAM_Butt.setGeometry(QtCore.QRect(640, 40, 151, 61))
        self.get_RAM_Butt.setObjectName("get_RAM_Butt")
        self.get_CPU_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.get_CPU_Butt.setGeometry(QtCore.QRect(640, 350, 151, 61))
        self.get_CPU_Butt.setObjectName("get_CPU_Butt")
        self.adb_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.adb_Butt.setGeometry(QtCore.QRect(10, 0, 281, 81))
        self.adb_Butt.setObjectName("adb_Butt")
        self.adb_devices_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.adb_devices_Butt.setGeometry(QtCore.QRect(300, 0, 311, 81))
        self.adb_devices_Butt.setObjectName("adb_devices_Butt")
        self.clear_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.clear_Butt.setGeometry(QtCore.QRect(10, 320, 121, 71))
        self.clear_Butt.setObjectName("clear_Butt")
        self.get_version_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.get_version_Butt.setGeometry(QtCore.QRect(10, 440, 111, 71))
        self.get_version_Butt.setObjectName("get_version_Butt")
        self.get_log_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.get_log_Butt.setGeometry(QtCore.QRect(400, 320, 121, 71))
        self.get_log_Butt.setObjectName("get_log_Butt")
        self.close_RAM_butt = QtWidgets.QPushButton(self.centralWidget)
        self.close_RAM_butt.setGeometry(QtCore.QRect(640, 100, 151, 61))
        self.close_RAM_butt.setObjectName("close_RAM_butt")
        self.close_CPU_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.close_CPU_Butt.setGeometry(QtCore.QRect(640, 410, 151, 61))
        self.close_CPU_Butt.setObjectName("close_CPU_Butt")
        self.path_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.path_Butt.setGeometry(QtCore.QRect(420, 140, 51, 28))
        self.path_Butt.setObjectName("path_Butt")
        self.RAM_log_text = QtWidgets.QTextBrowser(self.centralWidget)
        self.RAM_log_text.setGeometry(QtCore.QRect(790, 40, 321, 241))
        self.RAM_log_text.setTabChangesFocus(False)
        self.RAM_log_text.setOpenExternalLinks(False)
        self.RAM_log_text.setObjectName("RAM_log_text")
        self.CPU_log_text = QtWidgets.QTextBrowser(self.centralWidget)
        self.CPU_log_text.setGeometry(QtCore.QRect(790, 350, 321, 241))
        self.CPU_log_text.setObjectName("CPU_log_text")
        self.start_adb_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.start_adb_Butt.setGeometry(QtCore.QRect(10, 510, 261, 81))
        self.start_adb_Butt.setObjectName("start_adb_Butt")
        self.close_adb_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.close_adb_Butt.setGeometry(QtCore.QRect(280, 510, 271, 81))
        self.close_adb_Butt.setObjectName("close_adb_Butt")
        self.range_ram_text = QtWidgets.QLineEdit(self.centralWidget)
        self.range_ram_text.setGeometry(QtCore.QRect(930, 10, 51, 21))
        self.range_ram_text.setObjectName("range_ram_text")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(990, 10, 72, 15))
        self.label_2.setObjectName("label_2")
        self.checkBox_jietu = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_jietu.setEnabled(True)
        self.checkBox_jietu.setGeometry(QtCore.QRect(770, 10, 161, 19))
        self.checkBox_jietu.setTabletTracking(False)
        self.checkBox_jietu.setAcceptDrops(False)
        self.checkBox_jietu.setObjectName("checkBox_jietu")
        self.ram_csv_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.ram_csv_Butt.setGeometry(QtCore.QRect(640, 160, 151, 61))
        self.ram_csv_Butt.setObjectName("ram_csv_Butt")
        self.cpu_csv_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.cpu_csv_Butt.setGeometry(QtCore.QRect(640, 470, 151, 61))
        self.cpu_csv_Butt.setObjectName("cpu_csv_Butt")
        self.clean_ram_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.clean_ram_Butt.setGeometry(QtCore.QRect(640, 220, 151, 61))
        self.clean_ram_Butt.setObjectName("clean_ram_Butt")
        self.clean_cpu_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.clean_cpu_Butt.setGeometry(QtCore.QRect(640, 530, 151, 61))
        self.clean_cpu_Butt.setObjectName("clean_cpu_Butt")
        self.jietu_Butt = QtWidgets.QPushButton(self.centralWidget)
        self.jietu_Butt.setGeometry(QtCore.QRect(140, 320, 121, 71))
        self.jietu_Butt.setObjectName("jietu_Butt")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 320, 121, 71))
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 220, 409, 21))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 6, 1, 1)
        self.video_start_butt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.video_start_butt.setObjectName("video_start_butt")
        self.gridLayout_3.addWidget(self.video_start_butt, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 3, 1, 1)
        self.video_stop_butt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.video_stop_butt.setObjectName("video_stop_butt")
        self.gridLayout_3.addWidget(self.video_stop_butt, 0, 5, 1, 1)
        self.time_sec_text = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.time_sec_text.setObjectName("time_sec_text")
        self.gridLayout_3.addWidget(self.time_sec_text, 0, 2, 1, 1)
        self.time_min_text = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.time_min_text.setCursorPosition(1)
        self.time_min_text.setPlaceholderText("")
        self.time_min_text.setObjectName("time_min_text")
        self.gridLayout_3.addWidget(self.time_min_text, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "测试部ADB工具集"))
        self.get_Activity_Butt.setText(_translate("MainWindow", "获取当前界面包名"))
        self.install_Butt.setText(_translate("MainWindow", "包安装"))
        self.uninstall_Butt.setText(_translate("MainWindow", "包卸载"))
        self.get_RAM_Butt.setText(_translate("MainWindow", "APK内存占用查看"))
        self.get_CPU_Butt.setText(_translate("MainWindow", "APKCPU占用查看"))
        self.adb_Butt.setText(_translate("MainWindow", "ADB环境检测"))
        self.adb_devices_Butt.setText(_translate("MainWindow", "查看手机连接状态"))
        self.clear_Butt.setText(_translate("MainWindow", "清除应用数据与缓存"))
        self.get_version_Butt.setText(_translate("MainWindow", "查看安卓版本"))
        self.get_log_Butt.setText(_translate("MainWindow", "日志导出"))
        self.close_RAM_butt.setText(_translate("MainWindow", "关闭内存查看"))
        self.close_CPU_Butt.setText(_translate("MainWindow", "关闭CPU查看"))
        self.path_Butt.setText(_translate("MainWindow", "加载"))
        self.start_adb_Butt.setText(_translate("MainWindow", "打开adb进程"))
        self.close_adb_Butt.setText(_translate("MainWindow", "关闭adb进程"))
        self.range_ram_text.setText(_translate("MainWindow", "50"))
        self.label_2.setText(_translate("MainWindow", "M进行截图"))
        self.checkBox_jietu.setText(_translate("MainWindow", "一秒内内存增长超过"))
        self.ram_csv_Butt.setText(_translate("MainWindow", "内存数据存为csv"))
        self.cpu_csv_Butt.setText(_translate("MainWindow", "CPU数据存为CSV"))
        self.clean_ram_Butt.setText(_translate("MainWindow", "清空RAM数据"))
        self.clean_cpu_Butt.setText(_translate("MainWindow", "清空CPU数据"))
        self.jietu_Butt.setText(_translate("MainWindow", "当前屏幕截图"))
        self.pushButton.setText(_translate("MainWindow", "清空日志"))
        self.pushButton_2.setText(_translate("MainWindow", "保存录像"))
        self.video_start_butt.setText(_translate("MainWindow", "开始录制"))
        self.label.setText(_translate("MainWindow", "分钟"))
        self.label_3.setText(_translate("MainWindow", "秒"))
        self.video_stop_butt.setText(_translate("MainWindow", "停止录制"))
        self.time_sec_text.setText(_translate("MainWindow", "0"))
        self.time_sec_text.setPlaceholderText(_translate("MainWindow", "0"))
        self.time_min_text.setText(_translate("MainWindow", "0"))



